name: Deploy the lambda using AWS SAM
"on":
  push:
    branches:
      - aws-sam
  workflow_dispatch: {}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build
      - run: >
          sam deploy --stack-name ${{ secrets.AWS_STACK_NAME }} \
          --on-failure DELETE \
          --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
          --tags map-migrated=d-server-01068mdjl5jze3 \
          --no-confirm-changeset \
          --parameter-overrides 'awsRole="${{ secrets.AWS_ARN_ROLE }}" \
          functionName="${{ secrets.LAMBDA_FUNCTION }}" \
          secretId="${{ secrets.SECRET_ID }}"
          githubOwner="${{ secrets.OWNER }}" \
          githubRepository="${{ secrets.REPOSITORY }}" \
          githubWorkflowName="${{ secrets.WORKFLOW_FILE_NAME }}" \
          githubBranch="${{ secrets.BRANCH }}" \
          githubJobFilter="${{ secrets.JOB_FILTER }}"' \